<Project Sdk="Microsoft.NET.Sdk">
	<PropertyGroup>
		<Company>MC2IT</Company>
		<Copyright>© MC2IT</Copyright>
		<Description>An Agicap API client library for .NET.</Description>
		<Product>Agicap for .NET</Product>
		<Version>0.4.0</Version>
	</PropertyGroup>

	<PropertyGroup>
		<AppendTargetFrameworkToOutputPath>false</AppendTargetFrameworkToOutputPath>
		<AssemblyName>Mc2it.Agicap.Tests</AssemblyName>
		<BaseOutputPath>obj</BaseOutputPath>
		<ImplicitUsings>enable</ImplicitUsings>
		<Nullable>enable</Nullable>
		<OutDir>../Binaries</OutDir>
		<RootNamespace>Mc2it.Agicap</RootNamespace>
		<SatelliteResourceLanguages>en</SatelliteResourceLanguages>
		<TargetFramework>net10.0</TargetFramework>
	</PropertyGroup>

	<ItemGroup>
		<PackageReference Include="Microsoft.NET.Test.Sdk" Version="18.*" />
		<PackageReference Include="MSTest" Version="4.*" />
		<ProjectReference Include="../Sources/Agicap.csproj" />
	</ItemGroup>

	<ItemGroup>
		<Using Include="Microsoft.VisualStudio.TestTools.UnitTesting" />
		<Using Include="Microsoft.VisualStudio.TestTools.UnitTesting.Assert" Static="true" />
	</ItemGroup>
</Project>
