namespace Mc2it.Agicap.PurchaseJournal;

/// <summary>
/// Represents an entry of the Agicap purchase journal.
/// </summary>
public class PurchaseJournalEntry {

	/// <summary>
	/// The accounting lines for each account to be recorded.
	/// </summary>
	public IList<AccountingLine> AccountingLines { get; set; } = [];

	/// <summary>
	/// A unique identifier generated by Agicap.
	/// </summary>
	public Guid AgicapUniqueId { get; set; }

	/// <summary>
	/// The billing date of the document.
	/// </summary>
	public DateTime BillingDate { get; set; }

	/// <summary>
	/// The date when the payment is due.
	/// </summary>
	public DateTime? DueDate { get; set; }

	/// <summary>
	/// The enriched invoice data.
	/// </summary>
	public object? InvoiceInformation => throw new NotImplementedException();

	/// <summary>
	/// The reference number of the document.
	/// </summary>
	public string InvoiceOrReceiptNumber { get; set; } = "";

	/// <summary>
	/// The description manually entered.
	/// </summary>
	public string Note { get; set; } = "";

	/// <summary>
	/// The number(s) of the purchase order(s).
	/// </summary>
	public IList<string> OrderNumbers { get; set; } = [];

	/// <summary>
	/// The extension of the original file.
	/// </summary>
	public string? OriginalFileExtension { get; set; }

	/// <summary>
	/// The URL of the original file.
	/// </summary>
	public Uri? OriginalFileUrl { get; set; }

	/// <summary>
	/// The payment method.
	/// </summary>
	public PaymentMethod? PaymentMethod { get; set; }

	/// <summary>
	/// The date when the service occurred.
	/// </summary>
	public DateTime? PerformanceDate { get; set; }

	/// <summary>
	/// The end date if time frame provided.
	/// </summary>
	public DateTime? PrepaidExpenseEndDate { get; set; }

	/// <summary>
	/// The start date if time frame provided.
	/// </summary>
	public DateTime? PrepaidExpenseStartDate { get; set; }

	/// <summary>
	/// The ERP external identifier of the supplier.
	/// <see langword="null"/> for anything other than an invoice or credit note, or when the supplier has no <see cref="Suppliers.Supplier.ErpId"/>.
	/// </summary>
	public string? SupplierErpExternalId { get; set; }

	/// <summary>
	/// The name of the supplier.
	/// </summary>
	public string SupplierOrMerchant { get; set; } = "";

	/// <summary>
	/// The title manually entered.
	/// </summary>
	public string Title { get; set; } = "";

	/// <summary>
	/// The type of the source document.
	/// </summary>
	public Typology Typology { get; set; } = Typology.OwedInvoice;

	/// <summary>
	/// A unique identifier generated by Agicap.
	/// </summary>
	public string UniqueId { get; set; } = "";
}
