<Project Sdk="Microsoft.NET.Sdk">
	<PropertyGroup>
		<Company>MC2IT</Company>
		<Copyright>© MC2IT</Copyright>
		<Description>An Agicap API client library for .NET.</Description>
		<Product>Agicap for .NET</Product>
		<Version>0.2.0</Version>
	</PropertyGroup>

	<PropertyGroup>
		<Authors>CedX</Authors>
		<IncludeSymbols>true</IncludeSymbols>
		<PackageIcon>Icon.png</PackageIcon>
		<PackageLicenseExpression>MIT</PackageLicenseExpression>
		<PackageReadmeFile>ReadMe.md</PackageReadmeFile>
		<PackageTags>accounting;agicap;api;client;sdk;treasury</PackageTags>
		<RepositoryUrl>https://github.com/MC2IT/Agicap.net.git</RepositoryUrl>
		<SymbolPackageFormat>snupkg</SymbolPackageFormat>
	</PropertyGroup>

	<PropertyGroup>
		<AppendTargetFrameworkToOutputPath>false</AppendTargetFrameworkToOutputPath>
		<AssemblyName>Mc2it.Agicap</AssemblyName>
		<HotReloadAutoRestart>true</HotReloadAutoRestart>
		<ImplicitUsings>enable</ImplicitUsings>
		<Nullable>enable</Nullable>
		<OutDir>../Binaries</OutDir>
		<RootNamespace>Mc2it.Agicap</RootNamespace>
		<TargetFramework>net10.0</TargetFramework>
	</PropertyGroup>

	<ItemGroup>
		<InternalsVisibleTo Include="$(AssemblyName).Tests" />
		<None Include="../Icon.png" Pack="true" PackagePath="" />
		<None Include="../ReadMe.md" Pack="true" PackagePath="" />
	</ItemGroup>
</Project>
