namespace Mc2it.Agicap;

using System.Net;
using System.Text.Json;
using System.Text.Json.Serialization;

/// <summary>
/// A machine-readable format for specifying errors in HTTP API responses based on RFC 7807.
/// </summary>
public class ProblemDetails {

	/// <summary>
	/// A human-readable explanation specific to this occurrence of the problem.
	/// </summary>
	public string Detail { get; set; } = "";

	/// <summary>
	/// The extension members.
	/// </summary>
	[JsonExtensionData]
	public IDictionary<string, JsonElement> Extensions { get; set; } = new Dictionary<string, JsonElement>();

	/// <summary>
	/// A URI reference that identifies the specific occurrence of the problem.
	/// </summary>
	public Uri? Instance { get; set; }

	/// <summary>
	/// The HTTP status code generated by the origin server for this occurrence of the problem.
	/// </summary>
	public int Status { get; set; } = (int) HttpStatusCode.BadRequest;

	/// <summary>
	/// A short, human-readable summary of the problem type.
	/// </summary>
	public string Title { get; set; } = "";

	/// <summary>
	/// A URI reference that identifies the problem type.
	/// </summary>
	public Uri? Type { get; set; }
}
