namespace Mc2it.Agicap.TreasuryBankJournal;

using System.Globalization;
using System.Text.Json.Serialization;

/// <summary>
///	Represents an entry of the Agicap treasury bank journal.
/// </summary>
public class BankJournalEntry {

	/// <summary>
	/// An optional ERP-specific external identifier for the bank accounting account.
	/// </summary>
	public string? AccountingAccountExternalId { get; set; }

	/// <summary>
	/// The accounting account number.
	/// </summary>
	public string AccountingAccountNumber { get; set; } = "";

	/// <summary>
	/// The accounting currency ISO code.
	/// </summary>
	public string AccountingCurrency { get; set; } = RegionInfo.CurrentRegion.ISOCurrencySymbol;

	/// <summary>
	/// A unique identifier generated by Agicap.
	/// </summary>
	public Guid AgicapUniqueId { get; set; }

	/// <summary>
	/// The bank account name.
	/// </summary>
	public string BankAccountName { get; set; } = "";

	/// <summary>
	/// The banking transaction causale.
	/// </summary>
	public string? Causale { get; set; }

	/// <summary>
	/// The bank journal entry counterparts.
	/// </summary>
	public IList<Counterpart> Counterparts { get; set; } = [];

	/// <summary>
	/// The credit value in accounting currency.
	/// </summary>
	public decimal? CreditInAccountingCurrency { get; set; }

	/// <summary>
	/// The credit value in original currency.
	/// </summary>
	public decimal? CreditInOriginalCurrency { get; set; }

	/// <summary>
	/// The debit value in accounting currency.
	/// </summary>
	public decimal? DebitInAccountingCurrency { get; set; }

	/// <summary>
	/// The debit value in original currency.
	/// </summary>
	public decimal? DebitInOriginalCurrency { get; set; }

	/// <summary>
	/// A free-text memo for the bank journal entry.
	/// </summary>
	public string? EntryMemo { get; set; }

	/// <summary>
	/// The exchange rate applied between the original currency amount and the accounting currency amount.
	/// </summary>
	public double? ExchangeRate { get; set; }

	/// <summary>
	/// A unique reference per entity generated by Agicap, designed to match reference formats expected by accounting systems.
	/// </summary>
	public string ExportEntryReference { get; set; } = "";

	/// <summary>
	/// The index of the bank journal entry in the bank journal (starts at 1).
	/// </summary>
	public int IndexInExport { get; set => field = Math.Max(1, value); } = 1;

	/// <summary>
	/// The index of the bank journal entry in the current year (starts at 1).
	/// </summary>
	public int IndexInYear { get; set => field = Math.Max(1, value); } = 1;

	/// <summary>
	/// The journal code.
	/// </summary>
	public string? JournalCode { get; set; }

	/// <summary>
	/// The bank journal entry name.
	/// </summary>
	public string Name { get; set; } = "";

	/// <summary>
	/// The original currency ISO code.
	/// </summary>
	public string OriginalCurrency { get; set; } = RegionInfo.CurrentRegion.ISOCurrencySymbol;

	/// <summary>
	/// The banking transaction payment date.
	/// </summary>
	public DateTime PaymentDate { get; set; }

	/// <summary>
	/// The journal entry type.
	/// </summary>
	public BankJournalEntryType Type { get; set; } = BankJournalEntryType.BANK;
}

/// <summary>
///	Defines the type of a bank journal entry.
/// </summary>
[JsonConverter(typeof(JsonStringEnumConverter<BankJournalEntryType>))]
public enum BankJournalEntryType {

	/// <summary>
	/// A bank journal entry.
	/// </summary>
	BANK,

	/// <summary>
	/// A cash-in-transit entry.
	/// </summary>
	CASH_IN_TRANSIT
}
