namespace Mc2it.Agicap.TreasuryBankJournal;

using System.Text.Json.Serialization;

/// <summary>
///	Provides information about the document associated with a counterpart.
/// </summary>
public class Document {

	/// <summary>
	/// The document issue date.
	/// </summary>
	public DateTime? DocumentIssueDate { get; set; }

	/// <summary>
	/// The document reference number.
	/// </summary>
	public string? DocumentReference { get; set; }

	/// <summary>
	/// The document type.
	/// </summary>
	public DocumentType DocumentType { get; set; } = DocumentType.OTHER;

	/// <summary>
	/// The external identifier of the owning entity in the source system.
	/// </summary>
	public string? ExternalEntityId { get; set; }

	/// <summary>
	/// The document identifier from the source system.
	/// </summary>
	public string? ExternalId { get; set; }

	/// <summary>
	/// The document due date.
	/// </summary>
	public DateTime OriginalDueDate { get; set; }

	/// <summary>
	/// A unique identifier generated by Agicap.
	/// </summary>
	public string UniqueId { get; set; } = "";
}

/// <summary>
///	Defines the type of a document.
/// </summary>
[JsonConverter(typeof(JsonStringEnumConverter<DocumentType>))]
public enum DocumentType {
	CLIENT_CREDIT_NOTE,
	CLIENT_INVOICE,
	CLIENT_QUOTE,
	OTHER,
	PROFORMA_INVOICE,
	PURCHASE_ORDER,
	SALES_ORDER,
	SUPPLIER_CREDIT_NOTE,
	SUPPLIER_INVOICE
}
