namespace Mc2it.Agicap.TreasuryBankJournal;

/// <summary>
///	Represents a reference to a previously exported journal entry linked to a counterpart.
/// </summary>
public class LinkedEntry {

	/// <summary>
	/// A unique identifier generated by Agicap.
	/// </summary>
	public Guid AgicapUniqueId { get; set; }

	/// <summary>
	/// The unique export reference of the linked entry.
	/// </summary>
	public string ExportEntryReference { get; set; } = "";
}
